### ISSUE TITLE
[Bug] Integration Test

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline#73]
https://github.com/opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline/blob/c9d2ff870de50db94d0c77f7e4f6d809cef29868/situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java#L170

This method throws error when index already exists.

**Comment by chenqi0805** [comment]
@kowshikn Thanks for the catch! Through investigation, it is a bug with Service map where we should check existence of index instead of index alias.

https://github.com/opendistro-for-elasticsearch/simple-ingest-transformation-utility-pipeline/blob/c9d2ff870de50db94d0c77f7e4f6d809cef29868/situp-plugins/elasticsearch/src/main/java/com/amazon/situp/plugins/sink/elasticsearch/ElasticsearchSink.java#L174

**Comment by chenqi0805** [comment]
Fixed via #74
